### ISSUE TITLE
Bug report: Duplicated vertices along every texture seam

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [saturday06/VRM-Addon-for-Blender#277]
## Describe the bug

When importing **ANY** VRM model, every single vertex located along a texture seam is duplicated. Vertices located on more than one texture seam are duplicated again for every additional texture seam they are attached to.

## To Reproduce

1. Go to File -> Import -> VRM
2. Click on a VRM model and import it
3. Click the mesh and hit Tab to enter Edit mode
4. When attempting to move vertices located along texture seams, (such as the bottoms of arms on VRoid models) the vertices behave VERY strangely. Attempting to select edge loops behaves incorrectly as well.

## Expected behavior

The model's vertices behave properly and aren't duplicated.

## Screenshots

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/61099225/32d2b0ae-50ad-4273-ac35-222ca2e21192)

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/61099225/de959a70-cad6-4e51-bf38-b067c60f5093)

## Desktop (please complete the following information)

- OS: Windows 10
- Blender 3.6 LTS
- Addon Version: 2.17.5, has existed since as early as April 2022

## Additional context

Originally I saw this with VRoid models but importing other VRMs has produced this exact same bug.

**Comment by saturday06** [comment]
Thanks for reporting!

The mesh loading process of this add-on uses the official glTF 2.0 add-on process, so please file a bug report there : https://github.com/KhronosGroup/glTF-Blender-IO/issues

By changing the extension of the VRM file to GLB, it can be directly read by the glTF 2.0 add-on, so please confirm that the same phenomenon is occurring there.

The VRM specification is defined as an extension of glTF 2.0, and the mesh is directly from glTF 2.0.

**Comment by NedFlanders2** [comment]
I have not seen this issue and i have been looking for these sorts of problems when importing well every time i import something i check for these sorts of issues. I did once see some lose geometry on one model but that was a long time ago. Edge loops and other stuff are fine when i test them and there is no doubles. 

Maybe something else is going on.

**Comment by comdost** [comment]
I get this issue often! Importing the model as .glb instead seems not to cause the same vertex duplication/separation. 
Likewise with custom normals, they get changed with the extension but remain if I import as .glb instead.

![006440](https://github.com/saturday06/VRM-Addon-for-Blender/assets/68844490/b78cec90-2d96-4a63-8020-a4497aff47ae)

**Comment by saturday06** [comment]
@comdost 

Thanks for the report. The bug where normals are broken on import [has been fixed](https://github.com/saturday06/VRM-Addon-for-Blender/commit/775084ff410fb448c256c6d53e4ace4af48eef34) in the latest version of the Blender add-on. Please make sure your add-on is up to the latest version, 2.20.16, restart and try again.

If it doesn't work even though it is the latest, please let me know your OS and Blender version.

Since this issue vertex deals with the duplicate bug, it will stay open even if the normal breaking bug is fixed.

**Comment by comdost** [comment]
Thank you for fixing the normals bug! I really appreciate it!

I tried did a clean reinstall of blender, and this time there is no split vertex issue. However upon importing my other extensions and changing my settings, the issue came back. Something else is messing with the extension! 🥴 I will keep testing to find out what that is.

**Comment by c4b4d4** [comment]
Has this been resolved? We experienced something similar when importing a VRM

**Comment by saturday06** [comment]
This issue has been resolved. If you have had a similar experience, please create a new issue.
