### ISSUE TITLE
Bug report: Python Traceback File "<frozen importlib._bootstrap>" ModuleNotFoundError: No module named 'io_scene_gltf2.io.com.gltf_io_debug'

### ISSUE THREAD

**Issue by Pinkyyyy** [saturday06/VRM-Addon-for-Blender#694]
## Describe the bug

When exporting a model that's been rigged as a VRM model regardless of settings this error pops up preventing export. I checked the GLTF addon and made sure that the "remove armature" option is disabled

## To Reproduce

Try to export model as VRM
Error.

## Expected behavior

Try to export model as VRM
No error.

## Screenshots

![photo_2025-01-03_21-46-05](https://github.com/user-attachments/assets/f9847b40-5cb0-4862-b34e-a2b9c481264e)

## Desktop (please complete the following information)

- OS: Windows 10
- Blender: 4.3.2
- Addon Version: 2.33.1

## Additional context

pls fix uwu

**Comment by saturday06** [comment]
Thanks for reporting!That error has been fixed in add-on version 2.33.1. However, your error message suggests that you may be running an older version, or that it may be an error with a different add-on.

Please check the add-on version again. Also, please check whether you are exporting VRM via a different add-on.

**Comment by Menithal** [comment]
Can confirm that i replicated this with the Add-On release from Blender Extensions, but when using the github version it is not replicated.

**Comment by Pinkyyyy** [comment]
> Can confirm that i replicated this with the Add-On release from Blender Extensions, but when using the github version it is not replicated.

Yes, i used the version from blender extensions, since they both have the same version number i thought they'd be the same... Interesting.

**Comment by saturday06** [comment]
No errors occurred in my environment (Windows 10 / Blender 4.3.2 / Add-on 2.33.1). I have uploaded a video showing it working correctly.

@Pinkyyyy  For the investigation, could you please either shoot and upload a video in the same way, or upload a .blend file?

https://github.com/user-attachments/assets/1f1e2299-a466-41ac-8325-d9c0aacd83d4

**Comment by AlejandroMoc** [comment]
Can confirm this still happens on latest version only when using the Add-On release from Blender Extensions. It still doesn't happen when using the GitHub release.

**Comment by saturday06** [comment]
@AlejandroMoc No errors occurred in my environment (Windows 11 / Blender 4.5.2 / Add-on 3.11.4).

There have been reports that uninstalling the extension and then reinstalling it successfully resolves the issue. Could you please try that?
